### PR TITLE
Add footer

### PR DESCRIPTION
**Pull request by markMounsey**
Request review of subject additions and changes

### CODE REVIEW

**Comment by Georgy5** [comment]
"A subsidary of CityDog" -nice  touch =o)
Please make the grey darker (icon standard colour). I find it too light at the moment on the  light grey background
and I'd like the icons for LinkeIn and Github removed. (You could make an argument for Github may be, but not LinkledIn)
- I know we're not really linking to these services, but when pitching it might catch a TAs eye
image

**Comment by Georgy5** [comment]
Looking at it some more, I'd also change the background colourof the footer, because with the same body background colour it makes it look like the footer is taller than it is.
Currently the Footer looks like:
image

**Review by Georgy5 — COMMENTED** [review]
Made footer icons and text darker. Changed background color to differentiate from banner background.

**Comment by Georgy5** [comment]
What colour should we make the Footer background?
image

**Comment by Georgy5** [comment]
Merge conflict on this branch
grafik
Peter, you moved the notice and alert below the yield - but now it will just take space between the Footer and the body.
The 'notice' and 'alert' <p> tags should be replaced by a _flashes partial anyway. And an Alert or Notice should appear at the top where a user will actually see the message.

**Comment by Georgy5** [comment]
What the merge conflict currently looks like: 
grafik

**Comment by markMounsey** [comment]
Screen Shot 2021-02-03 at 14 11 15

**Comment by Georgy5** [comment]
After conversation with Mark on Slack, I'll change the Navbar background colour to be the same as the footer's. Note we should still edit the Banner (for the picture to take up the whole banner height).

**Pull request merged**
